MemoPad/urls.py
from django.contrib import admin
from django.urls import path, include
from memo.views.views import Home

urlpatterns = [
    path('memo/', include('memo.urls')),
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
]

memo/urls.py
from django.urls import path
# from . import views



from memo.views import views
from memo.views.memo.views import MemoListView, MemoCreateView, MemoUpdateView, MemoDeleteView



app_name = 'memo'

urlpatterns = [
    path('', views.index, name='index'),

    ###
    path('memos', MemoListView.as_view(), name='list_memo'),
path('memos_edit/<int:pk>', MemoUpdateView.as_view(), name='edit_memo'),
path('memos_new', MemoCreateView.as_view(), name='create_memo'),
path('memos_delete/<int:pk>', MemoDeleteView.as_view(), name='delete_memo'),
]

memo/models.py
# from django.db import models

# Create your models here.

from django.db import models
from django.utils import timezone
from datetime import datetime

class Memo(models.Model):
    class Meta:
        verbose_name = 'Memo Table'
        verbose_name_plural = 'Memos Table'
        db_table = 'memo'

    content = models.CharField(verbose_name='メモ', max_length=100, default='', blank=True,null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    
    def __str__(self):
        return self.content + '(' + datetime(self.created_at).strftime('%Y/%m/%d %H:%M:%S') + ')'

memo/forms/memo/forms.py
from django import forms
from memo.models import Memo

class MemoForm(forms.ModelForm):
    class Meta:
        model = Memo
        fields = ['id', 'content', 'created_at']

    content = forms.CharField(
        label="Content",
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'size': '30'}),
    )

    created_at = forms.DateField(
        label='Created at',
        required=False,
        input_formats=['%Y-%m-%d'],
        widget=forms.TextInput(attrs={'size': '12'}),
    )

memo/views/memo/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
from django.utils import timezone
from memo.models import Memo
from memo.forms.memo.forms import MemoForm

# List of Memos
class MemoListView(generic.ListView):
    model = Memo
    queryset = Memo.objects.order_by('-created_at')
    # items per page
    paginate_by = 10
    template_name = "memo/list_memo.html"
    success_url = reverse_lazy('home')

# Create new Memo
class MemoCreateView(generic.CreateView):
    model = Memo
    form_class = MemoForm
    template_name = "memo/memo_form.html"
    success_url = reverse_lazy('memo:list_memo')
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_at = timezone.now()
        self.object.save()

        return redirect('memo:list_memo')

# Update Memo
class MemoUpdateView(generic.UpdateView):
    model = Memo
    form_class = MemoForm
    template_name = "memo/memo_form.html"
    success_url = reverse_lazy('memo:list_memo')
    object = None

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()

        return redirect('memo:list_memo')

# Remove Memo
class MemoDeleteView(generic.DeleteView):
    model = Memo
    success_url = reverse_lazy('memo:list_memo')
    object = None

    def get(self, request, *args, **kwargs):
        self.object = Memo.objects.get(pk=kwargs['pk'])
        self.object.delete()
        return redirect('memo:list_memo')

memo/views/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the memo’s index.")

class Home(generic.TemplateView):
    template_name = 'home.html'

    def get(self, request, *args, **kwargs):
        context = super(Home, self).get_context_data()
        context.update({'my_message': 'Welcome to my site'})
        return render(request, 'home.html', context)

templates/base.html
<!DOCTYPE html>
{# Project: MwmoPad! (Hello World!) #}
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        {# --- css --- #}
        <meta http-equiv="Content-Type" content="text/css">
        <style type="text/css">
        {% block extra_css %}{% endblock %}
        </style>
        <script language="javascript" type="text/javascript">
        {% block extra_javascript %}{% endblock %}
        </script>
    </head>
    <body>
        {% block header %}
        <div class="align-items-center bg-white border-bottom">
            <h5><a href="{% url 'home' %}">Hello World</a></h5>
        </div>
        {% endblock %}
        <div class="container">
            {% block content %}{% endblock %}
            {% block pagination_footer %}{% endblock %}
        </div>
        {# --- js --- #}
        {% block extra_js %}{% endblock %}
    </body>
</html>

templates/home.html
{# Project: MemoPad #}
{# HOME #}
{% extends "base.html" %}
{% block title %} MemoPad {% endblock %}
{% block content %}
    <br>
    <div class="container">
        <!-- Content -->
        <h3>Hello World!</h3>
        {{ my_message }}
        <br>
        <a id="memo_app" href="{% url 'memo:list_memo' %}">Listing Memos</a>
    </div>
{% endblock %}

templates/memo/list_memo.html
{# Project: MemoPad #}
{# List of Memo #}
{% extends "base.html" %}
{% block title %}List of Memo - MemoPad!{% endblock title %}
{% block content %}
    <br>
    <div class="container">
        <!-- Content -->
        <h3>Listing of Memos</h3>
        {% if object_list|length == 0 %}
            <p>No Memo Found</p>
        {% else %}
            <table class="table table-striped table-bordered">
                <tr>
                    <th style="width:40%;">Memo</th>
                    <th style="width:30%;">Date</th>
                    <th>Edit</th>
                    <th>Remove</th>
                </tr>
                <tbody>
                    {% for memo in object_list %}
                    <tr>
                        <td>{{ memo.content }}</td>
                        <td>{{ memo.created_at }}</td>
                        <td align="center">
                            <a id="edit_btn" href="{% url 'memo:edit_memo' pk=memo.id %}">Edit</a>
                        </td>
                        <td align="center">
                            <a id="delete_btn" href="{% url 'memo:delete_memo' pk=memo.id %}">Remove</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
        <br>
        <a id="new_memo_link" href="{% url 'memo:create_memo' %}">Create New Memo</a><br />
        <a id="home_link" href="{% url 'home' %}">Back to Home</a>
    </div>
{% endblock content %}

templates/memo/memo_form.html
{# Project: MemoPad #}
{# Memo nput form #}
{% extends "base.html" %}
{% block title %}Editing Memo - Hello World!{% endblock %}
{% block content %}
    <br>
    <div class="container">
        <h4>Edit memo</h4>
        {% if form.errors and form.errors is not None and id != '0' %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-error">
                        <strong>・{{ field.label|escape }}:{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-error">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <label>{{ form.content.label }}</label>
            {{ form.content }} <br />
            <input type="submit" value="Save" id="submit_btn">
        </form>
        <br>
        <a id="list_link" href="{% url 'memo:list_memo' %}">Back to List</a>
    </div>
{% endblock %}